version: '3'

services:

  apache-php:
    container_name: framework-apache-php
    build: docker
    links:
      - database
    ports:
      - 9003:80
    volumes:
      - ./:/var/www/html
    restart: always

  # Banco de dados para testes
  database:
    container_name: framework-mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "framework_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    ports:
      - 9004:3306
    restart: always

  # Ferramenta para documentar a api
  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    ports:
      - 9005:8080
    restart: always
    environment:
      BASE_URL: "/"
      SWAGGER_JSON: "/swagger.json"
    volumes:
      - ./api/docs/swagger.json:/swagger.json
